services:
  ministack:
    image: ministackorg/ministack:latest
    container_name: ministack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,rds
      - DEBUG=0
    volumes:
      - ministack_data:/var/lib/localstack

volumes:
  ministack_data:
