version: "3.8"

services:
  ministack:
    image: ministackorg/ministack:latest
    container_name: ministack_iaas
    ports:
      - "4566:4566"
    volumes:
      # Baris ini yang akan menyimpan data fisik secara permanen!
      - ./ministack_data:/tmp/ministack
    restart: unless-stopped
